<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Entrevista extends Model
{
    protected $table = 'entrevistas';

    protected $fillable = [
        'curp',
        'hechos',
        'ocurrio_domicilio_victima',
        'especifica_domicilio',
        'sector',
        'ocurrio_extranjero',
        'fecha_hecho',
        'hora_hecho',
        'dia_festivo',
        'conoce_autoridad_asunto',
        'canalizado_cabi',
        'especifique_tipo_violencia',
        'victima_delicuencia_organizada',
        'relacion_denuncia',
        'relacionado_orientacion_identidad_genero',
        'especifique_efecto_fisico',
        'especifique_consecuencia_sexual',
        'especifique_efecto_psicologico',
        'especifique_economicos_patrimonial',
        'especifique_agente_lesion',
        'especifique_aerea_anatomica_lesionada',
        'vive_extranjero',
        'fecha_nacimiento',
        'edad',
        'telefono',
        'correo',
        'id_orientacion_sexual',
        'id_identidad_genero',
        'id_estado_civil',
        'id_ultimo_grado_estudios',
        'id_ingreso_promedio_mensual',
        'id_actividad',
        'realiza_mas_actividades',
        'id_servicio_medico',
        'codigo_postal',
        'colonia',
        'estado',
        'municipio',
        'localidad',
        'calle',
        'num_ext',
        'num_int',
        'entre_calles',
        'referencias',
        'zona',
        'migrante',
        'pertenece_pueblo_indigena',
        'autoidentificacion_etnica',
        'tiene_discapacidad',
        'id_discapacidad',
        'discapacidad_causada_violencia',
        'enfermedad_cronica_degenerativa',
        'trastorno_neurologico_mental',
        'tratado_medicamente_actualmente',
        'embarazo',
        'semanas_embarazo',
        'tiene_dependientes',
        'vive_situacion_calle',
        'tiene_adiccion',
        'conducta',
        'conoce_agresor',
        'nombre_agresor',
        'edad_agresor',
        'sexo_agresor',
        'id_vinculo_agresor',
        'id_identidad_genero_agresor',
        'id_orientacion_sexual_agresor',
        'vive_domicilio_victima',
        'codigo_postal_agresor',
        'colonia_agresor',
        'estado_agresor',
        'municipio_agresor',
        'calle_agresor',
        'num_ext_agresor',
        'num_int_agresor',
        'entre_calles_agresor',
        'referencias_agresor',
        'zona_agresor',
        'id_ultimo_grado_estudios_agresor',
        'id_ingreso_promedio_mensual_agresor',
        'id_ocupacion_agresor',
        'acceso_armas_agresor',
        'id_armas_agresor',
        'acceso_drogas_agresor',
        'id_dependencia',
        'especifica_dependencia',
        'id_canalizacion',
        'fecha_canalizacion',
        'semananas_embarazo',
        'responsable',
        'observaciones',
        'nombre',
        'comentarios_ruta_antencion',
        'id_user_created',  // ← DEBE ESTAR AQUÍ

    ];
}
